<?php

declare(strict_types=1);

namespace Tests\Controller;

use PHPUnit\Framework\TestCase;
use RLSQ\Controller\Attribute\AttributeRouteLoader;
use RLSQ\Controller\Attribute\Route;
use RLSQ\HttpFoundation\Response;

class AttributeRouteLoaderTest extends TestCase
{
    private AttributeRouteLoader $loader;

    protected function setUp(): void
    {
        $this->loader = new AttributeRouteLoader();
    }

    public function testLoadSimpleRoutes(): void
    {
        $collection = $this->loader->load(SampleController::class);

        $this->assertSame(3, $collection->count());
    }

    public function testRouteProperties(): void
    {
        $collection = $this->loader->load(SampleController::class);

        $home = $collection->get('home');
        $this->assertNotNull($home);
        $this->assertSame('/', $home->getPath());
        $this->assertSame(['GET'], $home->getMethods());
        $this->assertStringContainsString('SampleController::index', $home->getController());
    }

    public function testRouteWithRequirements(): void
    {
        $collection = $this->loader->load(SampleController::class);

        $show = $collection->get('article_show');
        $this->assertNotNull($show);
        $this->assertSame('/article/{id}', $show->getPath());
        $this->assertSame('\d+', $show->getRequirement('id'));
    }

    public function testAutoGeneratedRouteName(): void
    {
        $collection = $this->loader->load(SampleController::class);

        // La route sans nom explicite doit avoir un nom auto-généré
        $all = $collection->all();
        $names = array_keys($all);

        $this->assertContains('home', $names);
        $this->assertContains('article_show', $names);
        // 3ème route a un nom auto-généré
        $this->assertCount(3, $names);
    }

    public function testClassPrefixRoute(): void
    {
        $collection = $this->loader->load(PrefixedController::class);

        $list = $collection->get('api_users');
        $this->assertNotNull($list);
        $this->assertSame('/api/users', $list->getPath());

        $detail = $collection->get('api_user_detail');
        $this->assertNotNull($detail);
        $this->assertSame('/api/users/{id}', $detail->getPath());
    }

    public function testLoadAll(): void
    {
        $collection = $this->loader->loadAll([
            SampleController::class,
            PrefixedController::class,
        ]);

        $this->assertSame(5, $collection->count());
    }
}

// --- Fixtures ---

class SampleController
{
    #[Route('/', name: 'home', methods: ['GET'])]
    public function index(): Response
    {
        return new Response('Home');
    }

    #[Route('/article/{id}', name: 'article_show', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function show(int $id): Response
    {
        return new Response('Article ' . $id);
    }

    #[Route('/contact', methods: ['GET', 'POST'])]
    public function contact(): Response
    {
        return new Response('Contact');
    }
}

#[Route('/api')]
class PrefixedController
{
    #[Route('/users', name: 'api_users', methods: ['GET'])]
    public function list(): Response
    {
        return new Response('Users');
    }

    #[Route('/users/{id}', name: 'api_user_detail', methods: ['GET'])]
    public function detail(int $id): Response
    {
        return new Response('User ' . $id);
    }
}
